title: PHP
meta_title: PHP Course
meta_keywords: php, free php course, learn php
author: Greycampus
image_file: http://www.greycampus.com/logos/main.png
toc:
 - { 
     Introduction: {
       title: Introduction,
       slug: introduction,
       topics: { history: History, features: Features }
     }, 
     Installation-Process: {
       title: Installation Process,
       slug: installation-process,
       topics: { install: Install, setup: Setup }
     },
     Variables: {
       title: Variables,
       slug: variables,
       topics: { local-variables: Local Variables, functional-parameters: Functional Parameters, global-variables: Global Variables, static-variables: Static Variables, constants: Constants }
     },
     Data-Types: {
       title: Data Types,
       slug: data-types,
       topics: { integers: integers }
     },
     Type-Casting: {
       title: Type Casting,
       slug: type-casting,
       topics: { casting: Casting }
     },
     Operators: {
       title: Operators,
       slug: operators,
       topics: { arithmetic-operators: Arithmetic Operators, comparision-operators: Comparision Operators, logical-operators: Logical Operators, assignment-operators: Assignment Operators, conditional-operators: Conditional Operators }
     },
     control-structures: {
       title: Control Structures,
       slug: control-structures,
       topics: { decision-making: Desicion Making, loops: Loops }
     },
     arrays: {
       title: Arrays,
       slug: arrays,
       topics: { arrays: Arrays }
     }
  }
