title: PHP
meta_title: PHP Course
meta_keywords: php, free php course, learn php
author: Greycampus
image_file: http://www.greycampus.com/logos/main.png
status: published
toc: 
  introduction:
    title: Introduction
    topics: 
      history: 
        title: History 
        examples: 
          program1: Program1 
      features: 
        title: Features
        examples:
          program1: Program2
 
  installation-process:
    title: Installation Process
    topics: 
      install: 
        title: Install
        examples:
          program1: Program1
          program2: Program2 
      setup: 
        title: Setup
        examples:
          program1: Program1
          program2: Program2