title: PHP
meta_title: PHP Course
meta_keywords: php, free php course, learn php
author: Greycampus
image_file: http://www.greycampus.com/logos/main.png
toc:
 - { 
     introduction: {
       slug: introduction,
       topics: { history: History, features: Features }
     }, 
     InstallationProcess: {
       slug: installation-process,
       topics: { install: Install, setup: Setup }
     },
     Variables: {
       slug: variables,
       topics: { local-variables: Local Variables, functional-parameters: Functional Parameters, global-variables: Global Variables, static-variables: Static Variables, constants: Constants }
     },
     DataTypes: {
       slug: data-types,
       topics: { integers: integers }
     }
  }
